"""AEAD credential vault for router credentials at rest.

Router passwords and private keys are stored in SQLite only as ciphertext.
Encryption uses Fernet (AES-128-CBC with HMAC-SHA256 authentication) from the
``cryptography`` package — a vetted, well-established authenticated-encryption
scheme. We never invent cryptography.

Key management
--------------
The operator supplies ``AUTH_VAULT_KEY``: a 32-byte urlsafe-base64 Fernet key
(generated by ``cryptography.fernet.Fernet.generate_key``).

When ``AUTH_VAULT_KEY`` is unset, ``SECRET_KEY`` is used as a fallback
derivation source *only when it differs from the placeholder*
``change-me-in-production`` (a SHA-256 derivation keeps the derived Fernet key
32 bytes). If neither a valid key nor a non-placeholder secret is configured,
encryption is unavailable and the app refuses to store router credentials.

The key is never logged and plaintext credentials are never written to logs.
"""

from __future__ import annotations

import base64
import hashlib
import logging
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken

from database.schema.router import configure_secret_codec

logger = logging.getLogger(__name__)

#: Weak default never used for encryption (see config.py).
PLACEHOLDER_SECRET_KEY = "change-me-in-production"

#: Explicit format marker distinguishing ciphertext from legacy plaintext.
ENC_PREFIX = "encv1:"


class VaultError(RuntimeError):
    """Credential encryption is unavailable or decryption failed."""


class CredentialVault:
    """Fernet-based authenticated encryption for router credentials at rest."""

    prefix = ENC_PREFIX

    def __init__(self, key: str) -> None:
        self._fernet = Fernet(key)

    def encrypt(self, plaintext: str) -> str:
        token = self._fernet.encrypt(plaintext.encode("utf-8"))
        return f"{self.prefix}{token.decode('ascii')}"

    def decrypt(self, stored: str) -> str:
        """Decrypt a stored value, failing safely on a wrong key or tampering."""
        if not stored.startswith(self.prefix):
            return stored
        try:
            token = self._fernet.decrypt(stored[len(self.prefix) :].encode("ascii"))
        except (InvalidToken, ValueError) as exc:
            raise VaultError(
                "Failed to decrypt a stored router credential: is AUTH_VAULT_KEY "
                "correct for this database?"
            ) from exc
        return token.decode("utf-8")


def build_vault_key(settings) -> str | None:
    """Resolve a Fernet key from settings, or ``None`` when none is configured.

    Raises :class:`VaultError` when ``AUTH_VAULT_KEY`` is set but malformed.
    """
    raw = (getattr(settings, "auth_vault_key", "") or "").strip()
    if raw:
        key = _as_fernet_key(raw)
        if key is None:
            raise VaultError(
                "AUTH_VAULT_KEY is not a valid Fernet key: expected a 32-byte "
                "urlsafe-base64 string (see cryptography.fernet.Fernet.generate_key)."
            )
        return key
    secret = (getattr(settings, "secret_key", "") or "").strip()
    if secret and secret != PLACEHOLDER_SECRET_KEY:
        digest = hashlib.sha256(secret.encode("utf-8")).digest()
        return base64.urlsafe_b64encode(digest).decode("ascii")
    return None


def _as_fernet_key(raw: str) -> str | None:
    try:
        Fernet(raw)
        return raw
    except (ValueError, TypeError):
        pass
    try:
        data = raw.encode("utf-8")
        if len(data) == 32:
            return base64.urlsafe_b64encode(data).decode("ascii")
    except (ValueError, TypeError):
        pass
    return None


def build_vault(settings) -> CredentialVault | None:
    """Return a configured vault, or ``None`` when no key is configured."""
    key = build_vault_key(settings)
    if key is None:
        return None
    return CredentialVault(key)


def ensure_credential_vault(settings, store) -> CredentialVault | None:
    """Configure the credential codec and migrate legacy plaintext.

    Called once at application startup:

    * No key configured but credentials already stored -> fail with a clear
      message (production must not silently read/write plaintext).
    * No key configured and no credentials -> warn and continue (development
      demo mode); saving a router then raises until a key is set.
    * Key configured -> install the codec on ``RouterRecord`` and encrypt any
      legacy plaintext credentials (idempotent).
    """
    codec = build_vault(settings)
    if codec is None:
        if store.has_credentials():
            raise VaultError(
                "Stored router credentials require an encryption key. Set "
                "AUTH_VAULT_KEY (recommended) or a non-default SECRET_KEY, then restart."
            )
        logger.warning(
            "No credential encryption key configured (AUTH_VAULT_KEY/SECRET_KEY). "
            "Router credentials will be refused until one is set."
        )
        configure_secret_codec(None)
        return None
    configure_secret_codec(codec)
    migrated = store.migrate_vault(codec)
    if migrated:
        logger.info("Encrypted %d stored router credential(s) at rest", migrated)
    return codec


def harden_database_permissions(database_url: str) -> None:
    """Tighten permissions on the credential-bearing SQLite database file.

    Non-destructive: only narrows to owner-only ``0600`` when the file exists
    and is not already more permissive; never touches the parent directory.
    """
    if not database_url.startswith("sqlite"):
        return
    path = database_url.removeprefix("sqlite:///")
    if not path or path in (":memory:",):
        return
    try:
        db_path = Path(path)
        if not db_path.is_file():
            return
        db_path.chmod(0o600)
    except OSError as exc:  # pragma: no cover - best effort on exotic setups
        logger.warning("Could not tighten permissions on %s: %s", path, exc)
