"""AEAD credential vault for router credentials at rest.

Router passwords and private keys are stored in SQLite only as ciphertext.
Encryption uses Fernet (AES-128-CBC with HMAC-SHA256 authentication) from the
``cryptography`` package — a vetted, well-established authenticated-encryption
scheme. We never invent cryptography.

Key management
--------------
The vault key is a 32-byte urlsafe-base64 Fernet key (generated by
``cryptography.fernet.Fernet.generate_key``). Resolution order on startup:

1. ``AUTH_VAULT_KEY`` — explicit operator override, always wins.
2. the persisted key file (``vault.key`` in the application data directory),
   so generated/derived keys survive restarts and existing ciphertext stays
   decryptable.
3. ``SECRET_KEY`` derived (SHA-256, *only* when it differs from the placeholder
   ``change-me-in-production``) — legacy fallback; the derived key is persisted
   to the key file on first use so later restarts no longer depend on it.
4. none of the above — a fresh cryptographically random key is generated and
   persisted to the key file (first-run bootstrap; self-hosted friendly).

The key file is created owner-only (``0600``). The key is never logged and
plaintext credentials are never written to logs. If router credentials are
already encrypted but no key is recoverable (no ``AUTH_VAULT_KEY``, no key
file), startup fails with an actionable error instead of reading ciphertext
back as garbage.
"""

from __future__ import annotations

import base64
import hashlib
import logging
import os
from pathlib import Path

from cryptography.fernet import Fernet, InvalidToken

from database.schema.router import configure_secret_codec

logger = logging.getLogger(__name__)

#: Weak default never used for encryption (see config.py).
PLACEHOLDER_SECRET_KEY = "change-me-in-production"

#: Explicit format marker distinguishing ciphertext from legacy plaintext.
ENC_PREFIX = "encv1:"

#: Name of the persisted vault key file inside the application data directory.
VAULT_KEY_FILENAME = "vault.key"


class VaultError(RuntimeError):
    """Credential encryption is unavailable or decryption failed."""


class CredentialVault:
    """Fernet-based authenticated encryption for router credentials at rest."""

    prefix = ENC_PREFIX

    def __init__(self, key: str) -> None:
        self._fernet = Fernet(key)

    def encrypt(self, plaintext: str) -> str:
        token = self._fernet.encrypt(plaintext.encode("utf-8"))
        return f"{self.prefix}{token.decode('ascii')}"

    def decrypt(self, stored: str) -> str:
        """Decrypt a stored value, failing safely on a wrong key or tampering."""
        if not stored.startswith(self.prefix):
            return stored
        try:
            token = self._fernet.decrypt(stored[len(self.prefix) :].encode("ascii"))
        except (InvalidToken, ValueError) as exc:
            raise VaultError(
                "Failed to decrypt a stored router credential: is AUTH_VAULT_KEY "
                "correct for this database?"
            ) from exc
        return token.decode("utf-8")


def _explicit_vault_key(settings) -> str | None:
    """Return the configured ``AUTH_VAULT_KEY``, or ``None`` when unset.

    Raises :class:`VaultError` when ``AUTH_VAULT_KEY`` is set but malformed.
    """
    raw = (getattr(settings, "auth_vault_key", "") or "").strip()
    if not raw:
        return None
    key = _as_fernet_key(raw)
    if key is None:
        raise VaultError(
            "AUTH_VAULT_KEY is not a valid Fernet key: expected a 32-byte "
            "urlsafe-base64 string (see cryptography.fernet.Fernet.generate_key)."
        )
    return key


def _derived_vault_key(settings) -> str | None:
    """Derive a Fernet key from ``SECRET_KEY``, or ``None`` when unusable.

    Only a non-placeholder secret is eligible; SHA-256 keeps the derived key
    32 bytes. This is the legacy fallback from the original key management.
    """
    secret = (getattr(settings, "secret_key", "") or "").strip()
    if not secret or secret == PLACEHOLDER_SECRET_KEY:
        return None
    digest = hashlib.sha256(secret.encode("utf-8")).digest()
    return base64.urlsafe_b64encode(digest).decode("ascii")


def build_vault_key(settings) -> str | None:
    """Resolve a Fernet key from settings, or ``None`` when none is configured.

    Mirrors the original resolution (explicit key, then ``SECRET_KEY``
    derivation); the persisted key file is only consulted by
    :func:`ensure_credential_vault`.
    """
    explicit = _explicit_vault_key(settings)
    if explicit is not None:
        return explicit
    return _derived_vault_key(settings)


def _as_fernet_key(raw: str) -> str | None:
    try:
        Fernet(raw)
        return raw
    except (ValueError, TypeError):
        pass
    try:
        data = raw.encode("utf-8")
        if len(data) == 32:
            return base64.urlsafe_b64encode(data).decode("ascii")
    except (ValueError, TypeError):
        pass
    return None


def build_vault(settings) -> CredentialVault | None:
    """Return a configured vault, or ``None`` when no key is configured."""
    key = build_vault_key(settings)
    if key is None:
        return None
    return CredentialVault(key)


def vault_key_path(settings) -> Path:
    """Location of the persisted vault key file (application data directory).

    The application data directory is the directory holding the SQLite
    database, so the key travels with the data it protects. Falls back to
    ``./data`` when the database URL is not a file-backed SQLite path.
    """
    url = (getattr(settings, "database_url", "") or "").strip()
    if url.startswith("sqlite:///"):
        path = url.removeprefix("sqlite:///")
        if path and path != ":memory:":
            return Path(path).parent / VAULT_KEY_FILENAME
    return Path("data") / VAULT_KEY_FILENAME


def _read_vault_key(path: Path) -> str | None:
    """Read and validate a persisted key, or ``None`` when the file is absent."""
    if not path.is_file():
        return None
    try:
        raw = path.read_text(encoding="utf-8").strip()
    except OSError:
        return None
    if not raw:
        return None
    key = _as_fernet_key(raw)
    if key is None:
        raise VaultError(
            f"Vault key file {path} does not contain a valid Fernet key. "
            "Restore the original key file or set AUTH_VAULT_KEY, then restart."
        )
    return key


def _persist_vault_key(path: Path, key: str) -> str:
    """Write ``key`` to ``path`` owner-only, returning the key in effect.

    Created with ``0600`` permissions via ``O_EXCL`` so an existing secret file
    is never clobbered; on a concurrent-boot race the already-written key wins
    and is returned instead.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    except FileExistsError:
        existing = _read_vault_key(path)
        if existing is None:
            raise VaultError(
                f"Refusing to overwrite unreadable vault key file {path}. "
                "Restore the original key file or set AUTH_VAULT_KEY, then restart."
            ) from None
        return existing
    with os.fdopen(fd, "w", encoding="utf-8") as handle:
        handle.write(key)
        handle.write("\n")
        handle.flush()
        os.fsync(handle.fileno())
    try:
        os.chmod(path, 0o600)
    except OSError:  # pragma: no cover - best effort on exotic filesystems
        logger.warning("Could not tighten permissions on %s", path)
    return key


def _tighten_key_file_permissions(path: Path) -> None:
    """Best-effort ``0600`` on an existing key file (e.g. restored from backup)."""
    try:
        path.chmod(0o600)
    except OSError:  # pragma: no cover - best effort on exotic setups
        logger.warning("Could not tighten permissions on %s", path)


def ensure_credential_vault(settings, store) -> CredentialVault:
    """Configure the credential codec and migrate legacy plaintext.

    Called once at application startup. Resolves the vault key (explicit
    ``AUTH_VAULT_KEY`` > persisted key file > ``SECRET_KEY`` derivation >
    freshly generated), persisting a generated/derived key to the data
    directory so restarts decrypt existing ciphertext. Fails with an actionable
    error when stored credentials are encrypted but no key is recoverable.
    """
    explicit = _explicit_vault_key(settings)
    key_file = vault_key_path(settings)
    if explicit is not None:
        codec = CredentialVault(explicit)
    else:
        persisted = _read_vault_key(key_file)
        if persisted is not None:
            codec = CredentialVault(persisted)
            _tighten_key_file_permissions(key_file)
        else:
            derived = _derived_vault_key(settings)
            if derived is not None:
                codec = CredentialVault(_persist_vault_key(key_file, derived))
                logger.info("Persisted the derived credential vault key at %s", key_file)
            else:
                if store.has_encrypted_credentials():
                    raise VaultError(
                        "A stored router credential is encrypted but its decryption "
                        "key cannot be recovered. Set AUTH_VAULT_KEY to the original "
                        f"key, or restore the vault key file at {key_file}, then restart."
                    )
                generated = Fernet.generate_key().decode("ascii")
                codec = CredentialVault(_persist_vault_key(key_file, generated))
                logger.info("Generated a new credential vault key at %s", key_file)
    configure_secret_codec(codec)
    migrated = store.migrate_vault(codec)
    if migrated:
        logger.info("Encrypted %d stored router credential(s) at rest", migrated)
    return codec


def harden_database_permissions(database_url: str) -> None:
    """Tighten permissions on the credential-bearing SQLite database file.

    Non-destructive: only narrows to owner-only ``0600`` when the file exists
    and is not already more permissive; never touches the parent directory.
    """
    if not database_url.startswith("sqlite"):
        return
    path = database_url.removeprefix("sqlite:///")
    if not path or path in (":memory:",):
        return
    try:
        db_path = Path(path)
        if not db_path.is_file():
            return
        db_path.chmod(0o600)
    except OSError as exc:  # pragma: no cover - best effort on exotic setups
        logger.warning("Could not tighten permissions on %s: %s", path, exc)
